<a href="https://colab.research.google.com/github/vlvsvenkat/DWDM/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.array([1,2,3])
print(x)

[1 2 3]


In [ ]:
y = np.array([[4,5,6],[7,8,9]])
print(y)

[[4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [ ]:
b = np.append(x,[6,4,2])
print(b)

[1 2 3 6 4 2]


In [ ]:
print("The elements in X before deleting",x)
newarray = np.delete(x,2) 
print("The elements in X after deleting",newarray)

The elements in X before deleting [1 2 3]
The elements in X after deleting [1 2]


In [ ]:
b = np.array([6,4,1,3,5,9])
b[b<4] = -1 # Elements less than 4 are replaced with "-1"
print(b)

[ 6  4 -1 -1  5  9]


In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print("The elements in a are",a)
print("The elements in b are",b)
print("Result after Addition",a+b)
print("Result after substraction",a-b)
print("Result after multiplication",a*b)
print("Result after division",a/b) 
print("Result after increasing the number to the power of 4",b**4) 
print("Result after applying sin and multiplying with 10",10*np.sin(a))
a[0] +=10 
print("Result after adding first element with 10",a)
print(np.dot(a,b)) 

The elements in a are [20 30 40 50]
The elements in b are [0 1 2 3]
Result after Addition [20 31 42 53]
Result after substraction [20 29 38 47]
Result after multiplication [  0  30  80 150]
Result after division [        inf 30.         20.         16.66666667]
Result after increasing the number to the power of 4 [ 0  1 16 81]
Result after applying sin and multiplying with 10 [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
Result after adding first element with 10 [30 30 40 50]
260


<ipython-input-9-57f6c50a45d6>:8: RuntimeWarning: divide by zero encountered in true_divide
  print("Result after division",a/b)


In [ ]:
a=np.arange(10)**3
print("Let's consider the elements",a)
print("The output of a[2] is", a[2]) 
print("The output of a[2:4] is",a[2:4])
print("The output of a[2:3] is",a[2:3]) 
print("The output of a[-1] is",a[-1])
print("The output of a[-2] is",a[-2]) 
print("The output of a[-5:-2] is",a[-5:-2]) 

Let's consider the elements [  0   1   8  27  64 125 216 343 512 729]
The output of a[2] is 8
The output of a[2:4] is [ 8 27]
The output of a[2:3] is [8]
The output of a[-1] is 729
The output of a[-2] is 512
The output of a[-5:-2] is [125 216 343]


In [ ]:
a=np.arange(12).reshape(4,3)**2 
print("The output of a[2] is",a)
print("The output of a[1:3] is",a[1:3]) 
print("The output of a[1:3,1:2] is",a[1:3,1:2]) 
print("The output of a[2,] is",a[2,])
print("The output of a[:3,] is",a[:3,])
print("The output of a[-1,] is",a[-1,])
print("The output of a[-1,-1] is",a[-1,-1]) 

The output of a[2] is [[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
The output of a[1:3] is [[ 9 16 25]
 [36 49 64]]
The output of a[1:3,1:2] is [[16]
 [49]]
The output of a[2,] is [36 49 64]
The output of a[:3,] is [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
The output of a[-1,] is [ 81 100 121]
The output of a[-1,-1] is 121


In [ ]:
a=np.arange(12).reshape(4,3)**2
print("Let's consider an array\n",a)
print("\n")
for i in a:
   print(i*2)

Let's consider an array
 [[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


[0 2 8]
[18 32 50]
[ 72  98 128]
[162 200 242]


In [ ]:
a=np.floor(10*np.random.random((3,4))) 
print("Let's consider a 1-D array\n",a)
print("After reshaping to 2 by 6 matrix\n",a.reshape(2,6))
print("To Flatten the array\n",a.ravel())
print("To transpose the array\n",a.T)

Let's consider a 1-D array
 [[0. 5. 5. 6.]
 [6. 0. 5. 9.]
 [9. 5. 0. 2.]]
After reshaping to 2 by 6 matrix
 [[0. 5. 5. 6. 6. 0.]
 [5. 9. 9. 5. 0. 2.]]
To Flatten the array
 [0. 5. 5. 6. 6. 0. 5. 9. 9. 5. 0. 2.]
To transpose the array
 [[0. 6. 9.]
 [5. 0. 5.]
 [5. 5. 0.]
 [6. 9. 2.]]
